# Generated by Django 6.0.6 on 2026-06-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
