# Generated by Django 6.0.6 on 2026-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_profile_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="skills",
            new_name="learn_skills",
        ),
        migrations.AddField(
            model_name="profile",
            name="teach_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
