# Generated by Django 6.0.6 on 2026-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_rename_skills_profile_learn_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="premium_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="premium_plan",
            field=models.CharField(default="free", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="premium_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
