# Generated by Django 6.0.6 on 2026-06-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_profile_is_premium_profile_premium_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="premium_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
