# Generated by Django 6.0.6 on 2026-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_profile_premium_ends_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=40)),
                ("mobile", models.IntegerField(max_length=15)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
