# Generated by Django 6.0.6 on 2026-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
    ]
