# Generated by Django 6.0.6 on 2026-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_alter_contactmessage_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(default="Open", max_length=20),
        ),
    ]
