# Generated by Django 6.0.6 on 2026-06-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_contactmessage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
